# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_editor_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_image_editor_window(object):
    def setupUi(self, image_editor_window):
        image_editor_window.setObjectName("image_editor_window")
        image_editor_window.resize(1113, 605)
        self.centralwidget = QtWidgets.QWidget(image_editor_window)
        self.centralwidget.setObjectName("centralwidget")
        self.original_image_label = QtWidgets.QLabel(self.centralwidget)
        self.original_image_label.setGeometry(QtCore.QRect(110, 30, 381, 321))
        self.original_image_label.setText("")
        self.original_image_label.setPixmap(QtGui.QPixmap("../images/examples-examples.jpg"))
        self.original_image_label.setScaledContents(True)
        self.original_image_label.setObjectName("original_image_label")
        self.changed_imag_label = QtWidgets.QLabel(self.centralwidget)
        self.changed_imag_label.setGeometry(QtCore.QRect(670, 30, 381, 321))
        self.changed_imag_label.setText("")
        self.changed_imag_label.setPixmap(QtGui.QPixmap("../images/examples-examples.jpg"))
        self.changed_imag_label.setScaledContents(True)
        self.changed_imag_label.setObjectName("changed_imag_label")
        self.checker_button = QtWidgets.QPushButton(self.centralwidget)
        self.checker_button.setGeometry(QtCore.QRect(980, 520, 121, 41))
        self.checker_button.setObjectName("checker_button")
        self.RGB_check_box = QtWidgets.QGroupBox(self.centralwidget)
        self.RGB_check_box.setGeometry(QtCore.QRect(770, 400, 105, 114))
        self.RGB_check_box.setObjectName("RGB_check_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.RGB_check_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.r_canal_check_box = QtWidgets.QCheckBox(self.RGB_check_box)
        self.r_canal_check_box.setObjectName("r_canal_check_box")
        self.verticalLayout.addWidget(self.r_canal_check_box)
        self.green_color__check_box_2 = QtWidgets.QCheckBox(self.RGB_check_box)
        self.green_color__check_box_2.setObjectName("green_color__check_box_2")
        self.verticalLayout.addWidget(self.green_color__check_box_2)
        self.blue_color_check_box = QtWidgets.QCheckBox(self.RGB_check_box)
        self.blue_color_check_box.setObjectName("blue_color_check_box")
        self.verticalLayout.addWidget(self.blue_color_check_box)
        self.convert_to_gray_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.convert_to_gray_check_box.setGeometry(QtCore.QRect(760, 550, 151, 20))
        self.convert_to_gray_check_box.setObjectName("convert_to_gray_check_box")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 380, 441, 197))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.contrast_label = QtWidgets.QLabel(self.layoutWidget)
        self.contrast_label.setObjectName("contrast_label")
        self.gridLayout.addWidget(self.contrast_label, 0, 0, 1, 1)
        self.contrast_slider = QtWidgets.QSlider(self.layoutWidget)
        self.contrast_slider.setOrientation(QtCore.Qt.Horizontal)
        self.contrast_slider.setObjectName("contrast_slider")
        self.gridLayout.addWidget(self.contrast_slider, 1, 0, 1, 1)
        self.gamma_slider = QtWidgets.QSlider(self.layoutWidget)
        self.gamma_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gamma_slider.setObjectName("gamma_slider")
        self.gridLayout.addWidget(self.gamma_slider, 1, 1, 1, 1)
        self.gaussian_label = QtWidgets.QLabel(self.layoutWidget)
        self.gaussian_label.setObjectName("gaussian_label")
        self.gridLayout.addWidget(self.gaussian_label, 2, 0, 1, 1)
        self.gaussian_slider = QtWidgets.QSlider(self.layoutWidget)
        self.gaussian_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gaussian_slider.setObjectName("gaussian_slider")
        self.gridLayout.addWidget(self.gaussian_slider, 3, 0, 1, 1)
        self.gamma_label = QtWidgets.QLabel(self.layoutWidget)
        self.gamma_label.setObjectName("gamma_label")
        self.gridLayout.addWidget(self.gamma_label, 0, 1, 1, 1)
        image_editor_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(image_editor_window)
        QtCore.QMetaObject.connectSlotsByName(image_editor_window)

    def retranslateUi(self, image_editor_window):
        _translate = QtCore.QCoreApplication.translate
        image_editor_window.setWindowTitle(_translate("image_editor_window", "MainWindow"))
        self.checker_button.setText(_translate("image_editor_window", "Check"))
        self.RGB_check_box.setTitle(_translate("image_editor_window", "RGB"))
        self.r_canal_check_box.setText(_translate("image_editor_window", "R"))
        self.green_color__check_box_2.setText(_translate("image_editor_window", "G"))
        self.blue_color_check_box.setText(_translate("image_editor_window", "B"))
        self.convert_to_gray_check_box.setText(_translate("image_editor_window", " Convert to gray scale"))
        self.contrast_label.setText(_translate("image_editor_window", "contrast"))
        self.gaussian_label.setText(_translate("image_editor_window", "gaussian blur"))
        self.gamma_label.setText(_translate("image_editor_window", "gamma"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    image_editor_window = QtWidgets.QMainWindow()
    ui = Ui_image_editor_window()
    ui.setupUi(image_editor_window)
    image_editor_window.show()
    sys.exit(app.exec_())
