# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'intro_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_intro_window(object):
    def setupUi(self, intro_window):
        intro_window.setObjectName("intro_window")
        intro_window.resize(629, 619)
        self.centralwidget = QtWidgets.QWidget(intro_window)
        self.centralwidget.setObjectName("centralwidget")
        self.intro_image_label = QtWidgets.QLabel(self.centralwidget)
        self.intro_image_label.setGeometry(QtCore.QRect(0, 0, 629, 619))
        self.intro_image_label.setText("")
        self.intro_image_label.setPixmap(QtGui.QPixmap("../images/logo.png"))
        self.intro_image_label.setObjectName("intro_image_label")
        self.info_text_label = QtWidgets.QLabel(self.centralwidget)
        self.info_text_label.setGeometry(QtCore.QRect(160, 520, 271, 41))
        self.info_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_text_label.setObjectName("info_text_label")
        intro_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(intro_window)
        QtCore.QMetaObject.connectSlotsByName(intro_window)

    def retranslateUi(self, intro_window):
        _translate = QtCore.QCoreApplication.translate
        intro_window.setWindowTitle(_translate("intro_window", "MainWindow"))
        self.info_text_label.setText(_translate("intro_window", "Click to continue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    intro_window = QtWidgets.QMainWindow()
    ui = Ui_intro_window()
    ui.setupUi(intro_window)
    intro_window.show()
    sys.exit(app.exec_())
