# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_start_window(object):
    def setupUi(self, start_window):
        start_window.setObjectName("start_window")
        start_window.resize(644, 677)
        start_window.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        start_window.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(start_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 180, 351, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.main_menu_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.main_menu_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.main_menu_layout.setContentsMargins(12, 0, 12, 0)
        self.main_menu_layout.setSpacing(10)
        self.main_menu_layout.setObjectName("main_menu_layout")
        self.image_load_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.image_load_button.setIconSize(QtCore.QSize(20, 19))
        self.image_load_button.setObjectName("image_load_button")
        self.main_menu_layout.addWidget(self.image_load_button)
        self.open_instruction_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.open_instruction_button.setObjectName("open_instruction_button")
        self.main_menu_layout.addWidget(self.open_instruction_button)
        self.open_description_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.open_description_button.setObjectName("open_description_button")
        self.main_menu_layout.addWidget(self.open_description_button)
        self.open_credits_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.open_credits_button.setObjectName("open_credits_button")
        self.main_menu_layout.addWidget(self.open_credits_button)
        start_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(start_window)
        QtCore.QMetaObject.connectSlotsByName(start_window)

    def retranslateUi(self, start_window):
        _translate = QtCore.QCoreApplication.translate
        start_window.setWindowTitle(_translate("start_window", "MainWindow"))
        self.image_load_button.setText(_translate("start_window", "CHECK IMAGE"))
        self.open_instruction_button.setText(_translate("start_window", "INSTRUCTIONS"))
        self.open_description_button.setText(_translate("start_window", "PROJECT DESCRIPTION"))
        self.open_credits_button.setText(_translate("start_window", "CREDITS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    start_window = QtWidgets.QMainWindow()
    ui = Ui_start_window()
    ui.setupUi(start_window)
    start_window.show()
    sys.exit(app.exec_())
